"""
HRMS Backend — Seed Data Script

Generates realistic seed data for the hackathon demo:
- 25+ employees across 5 departments.
- 3 months of attendance (with gaps/streaks).
- 15+ leave requests (Pending/Approved/Rejected).
- 8+ projects (all statuses).
- 3 months of payroll records.

Idempotent: Cleans up any existing seed data (identified by @seed.hrms.com)
before generating new data. Uses the service-role client to bypass RLS.
"""

import sys
import os
import random
from datetime import date, timedelta, datetime
from faker import Faker

# Add project root to path so we can import from backend.app
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from backend.app.database import get_service_client

fake = Faker()
sc = get_service_client()

SEED_DOMAIN = "@seed.hrms.com"
DEPARTMENTS = ["Engineering", "Design", "Marketing", "Sales", "HR"]
JOB_TITLES = {
    "Engineering": ["Software Engineer", "Senior Engineer", "DevOps Engineer", "Frontend Developer"],
    "Design": ["UI/UX Designer", "Product Designer", "Graphic Designer"],
    "Marketing": ["Marketing Manager", "Content Strategist", "SEO Specialist"],
    "Sales": ["Sales Representative", "Account Executive", "Sales Manager"],
    "HR": ["HR Generalist", "Recruiter", "HR Manager"],
}

NUM_EMPLOYEES = 25
TODAY = date.today()
START_DATE = TODAY - timedelta(days=90)


def clean_existing_seed_data():
    print(f"🧹 Cleaning up existing seed data (users ending in {SEED_DOMAIN})...")
    # Query public.users to get the IDs
    res = sc.table("users").select("id").like("email", f"%{SEED_DOMAIN}").execute()
    if not res.data:
        print("   No existing seed data found.")
        return

    ids = [row["id"] for row in res.data]
    
    # Wipe heavy child tables first to prevent cascade timeouts during delete_user
    sc.table("attendance").delete().in_("user_id", ids).execute()
    sc.table("leaves").delete().in_("user_id", ids).execute()
    sc.table("payroll").delete().in_("user_id", ids).execute()
    sc.table("projects").delete().in_("assigned_to", ids).execute()
    sc.table("projects").delete().in_("created_by", ids).execute()
    sc.table("profiles").delete().in_("user_id", ids).execute()

    # Delete from auth.users using the admin API.
    for row in res.data:
        try:
            sc.auth.admin.delete_user(row["id"])
        except Exception as e:
            print(f"   ⚠️ Failed to delete user {row['id']}: {e}")
    print(f"   ✅ Cleaned up {len(res.data)} existing users.")


def create_users_and_profiles():
    print(f"👥 Creating {NUM_EMPLOYEES} users and profiles...")
    users = []
    
    # Ensure we have at least 1 HR and 1 Admin
    roles = ["Admin", "HR"] + ["Employee"] * (NUM_EMPLOYEES - 2)
    random.shuffle(roles)

    for i in range(NUM_EMPLOYEES):
        role = roles[i]
        dept = "HR" if role == "HR" else ("Engineering" if role == "Admin" else random.choice(DEPARTMENTS))
        title = random.choice(JOB_TITLES[dept])
        first_name = fake.first_name()
        last_name = fake.last_name()
        full_name = f"{first_name} {last_name}"
        email = f"{first_name.lower()}.{last_name.lower()}.{i}{SEED_DOMAIN}"

        # 1. Create auth user
        resp = sc.auth.admin.create_user({
            "email": email,
            "password": "SeedPassword123!",
            "email_confirm": True,
            "user_metadata": {
                "role": role,
                "full_name": full_name,
            }
        })
        user_id = resp.user.id
        
        # 2. Update the auto-created profile with more realistic data
        # The auto-created profile is generated by an auth trigger.
        # We DELETE it and INSERT a new one to bypass the BEFORE UPDATE column-level
        # trigger which restricts updates based on auth.uid() (which is null for service_role).
        sc.table("profiles").delete().eq("user_id", user_id).execute()
        sc.table("profiles").insert({
            "user_id": user_id,
            "full_name": full_name,
            "phone": fake.phone_number()[:15],
            "address": fake.city(),
            "job_title": title,
            "department": dept,
            "designation": "Manager" if "Manager" in title else "Individual Contributor",
            "skills": random.sample(["Python", "React", "Figma", "AWS", "SEO", "Salesforce", "Communication"], k=random.randint(2, 5)),
            "joining_date": (TODAY - timedelta(days=random.randint(100, 1000))).isoformat()
        }).execute()

        users.append({"id": user_id, "role": role, "email": email, "department": dept})

    print("   ✅ Users created.")
    return users


def create_attendance(users):
    print("📅 Generating 3 months of attendance...")
    attendance_records = []
    
    # Generate realistic patterns
    for user in users:
        current_date = START_DATE
        while current_date <= TODAY:
            # Skip weekends usually
            if current_date.weekday() < 5:
                # 85% Present, 5% Absent, 5% Half-day, 5% On Leave
                rand = random.random()
                if rand < 0.85:
                    status = "Present"
                    hours = round(random.uniform(7.5, 9.0), 1)
                elif rand < 0.90:
                    status = "Absent"
                    hours = 0
                elif rand < 0.95:
                    status = "Half-day"
                    hours = round(random.uniform(3.5, 4.5), 1)
                else:
                    status = "On Leave"
                    hours = 0
                
                # Check-in time (e.g. 8:30 AM to 9:30 AM)
                check_in_time = datetime.combine(current_date, datetime.min.time()) + timedelta(hours=8, minutes=random.randint(30, 90))
                # Check-out time based on hours
                check_out_time = check_in_time + timedelta(hours=hours) if hours > 0 else None

                attendance_records.append({
                    "user_id": user["id"],
                    "date": current_date.isoformat(),
                    "check_in": check_in_time.isoformat() if hours > 0 else None,
                    "check_out": check_out_time.isoformat() if hours > 0 else None,
                    "hours": hours if hours > 0 else None,
                    "status": status,
                    "marked_by": "employee" if hours > 0 else "system"
                })
            current_date += timedelta(days=1)
    
    # Batch insert in chunks of 500
    chunk_size = 500
    for i in range(0, len(attendance_records), chunk_size):
        sc.table("attendance").insert(attendance_records[i:i+chunk_size]).execute()
    print(f"   ✅ {len(attendance_records)} attendance records inserted.")


def create_leaves(users):
    print("🌴 Generating leave requests...")
    leaves = []
    statuses = ["Pending", "Approved", "Rejected"]
    types = ["Paid", "Sick", "Unpaid"]
    
    # Create 20 leaves
    for _ in range(20):
        u = random.choice(users)
        start = START_DATE + timedelta(days=random.randint(0, 80))
        end = start + timedelta(days=random.randint(0, 5))
        status = random.choices(statuses, weights=[0.4, 0.5, 0.1])[0]
        
        leaves.append({
            "user_id": u["id"],
            "leave_type": random.choice(types),
            "start_date": start.isoformat(),
            "end_date": end.isoformat(),
            "reason": fake.sentence(),
            "status": status,
            "admin_comments": "Approved based on policy." if status == "Approved" else ("Not enough balance." if status == "Rejected" else None)
        })
    
    sc.table("leaves").insert(leaves).execute()
    print(f"   ✅ {len(leaves)} leave requests inserted.")


def create_projects(users):
    print("🚀 Generating projects...")
    projects = []
    admins = [u for u in users if u["role"] == "Admin"]
    if not admins:
        return
    admin_id = admins[0]["id"]
    
    statuses = ["Not Started", "In Progress", "Review", "Completed"]
    priorities = ["Low", "Medium", "High", "Critical"]
    
    for _ in range(12):
        assigned_to = random.choice(users)["id"]
        projects.append({
            "title": f"{fake.catch_phrase()} Project",
            "description": fake.paragraph(),
            "assigned_to": assigned_to,
            "deadline": (TODAY + timedelta(days=random.randint(-10, 60))).isoformat(),
            "priority": random.choice(priorities),
            "status": random.choice(statuses),
            "created_by": admin_id
        })
    
    sc.table("projects").insert(projects).execute()
    print(f"   ✅ {len(projects)} projects inserted.")


def create_payroll(users):
    print("💰 Generating payroll records...")
    payrolls = []
    months = [
        (TODAY.month - 2 if TODAY.month > 2 else TODAY.month + 10, TODAY.year if TODAY.month > 2 else TODAY.year - 1),
        (TODAY.month - 1 if TODAY.month > 1 else 12, TODAY.year if TODAY.month > 1 else TODAY.year - 1),
        (TODAY.month, TODAY.year)
    ]
    
    for user in users:
        base = random.randint(4000, 12000)
        for month, year in months:
            deductions = random.randint(100, 500)
            payrolls.append({
                "user_id": user["id"],
                "base_salary": base,
                "deductions": deductions,
                "month": month,
                "year": year
            })
            
    # Batch insert
    chunk_size = 500
    for i in range(0, len(payrolls), chunk_size):
        sc.table("payroll").insert(payrolls[i:i+chunk_size]).execute()
    print(f"   ✅ {len(payrolls)} payroll records inserted.")


def main():
    try:
        clean_existing_seed_data()
        users = create_users_and_profiles()
        create_attendance(users)
        create_leaves(users)
        create_projects(users)
        create_payroll(users)
        print("\n🎉 Seed data generation complete!")
    except Exception as e:
        print(f"\n❌ Error during seeding: {e}")


if __name__ == "__main__":
    main()
